### ISSUE TITLE
Index page to navigate all quizzes

### ISSUE THREAD

**Issue by shiffman** [ITPNYU/ICM-Quizzes#3]
Better yes, use Jekyll for templating and incorporate more design / navigation elements.

**Comment by yining1023** [comment]
I added navigation with a jekyll template(https://github.com/willianjusten/cards-jekyll-template): 
Here is a demo: https://yining1023.github.io/

It has nice adding tag, live search features too. We can customize it more.

(I didn't use a github project website for this Jekyll website for now because it introduces some complexity. The url, http://yining1023.github.io/repository-name, will break references to images and other html files)

Here's my repository: https://github.com/yining1023/yining1023.github.io. I haven't made a PR because I'm not sure what's the best way to integrate this to the original repository.

**Comment by cshirky** [comment]
In Week 1 at https://yining1023.github.io/, s/crateCanvas/createCanvas/ in
the source for the page.tags loop. Couldn't find it in the repo.

-clay

**Comment by shiffman** [comment]
@yining1023 this is terrific!  I'm busy prepping for A2Z for tomorrow, but I can look at integrating it with you Tues/Wed.
